### PR TITLE
Added exponential observation class

### PR DESCRIPTION
**Pull request by em812**

### CODE REVIEW

**Comment by slinderman** [comment]
Thanks @em812!  @bantin could you please do a code review?

**Comment by bantin** [comment]
Hi @em812 ! Thanks for the PR. I have a few comments, but I think this is nearly ready.

1) Currently, running the `example/hmm_exponential.py` script fails for me, because the exponential observation model needs to be added to the list of observation classes in `hmm.py` (this list starts on line 79). I think there's a chance that you made this change on your local work tree, but it didn't get committed. 

2) In addition to adding an example in the `examples` folder, I'd like to have a unit test which ensures that we can instantiate an HMM object with exponential observations. This will help us avoid regressions, etc, in the future. The best way to do this is to add "exponential" to the list of observation names in `tests/test_basics.py`. The list I'm talking about starts on line 24 of that file.

3) Lastly, some style comments. There are places where things have been commented out (e.g at the end of `examples/hmm_exponential.py`, and in the m_step function for the new observations class in `ssm/observations.py`.  If these lines are no longer being used, I'd like to have them taken out.

Thank you!

**Comment by em812** [comment]
Hi @bantin! Thanks for the review. I pushed the changes you asked for.

**Comment by bantin** [comment]
@em812 Thank you! Looks good to me, merging.

**Pull request merged**
